libnbc fix for iallreduce count*extent overflowing int
open-mpi/ompi pull request #10082
Opened 2022-03-07 23:32 UTC by markalle

In the libnbc iallreduce ring algorithm at -np 4, if the datatype is
MPI_LONG_LONG of 8bytes and a count is used like 1.5 billion so the
total bytes is 12Gb, the offsets for some of the iterations were going
negative.

gist for testcase:
    https://gist.github.com/markalle/61e05fed6de4cd201d5e7d22b0c175a1
% mpicc -o x iallreduce_overflow.c
% mpirun -np 4 --mca coll_libnbc_iallreduce_algorithm 1 ./x 12000000000

The testcase picks a random number of bytes for the allreduce buffer if one
isn't specified on the command line.

Signed-off-by: Mark Allen <markalle@us.ibm.com>

2022-03-07 23:49 UTC, gpaulsen requested changes
Looks good, other than Copyright line correction.

2022-03-07 23:49 UTC, gpaulsen commented on ompi/mca/coll/libnbc/nbc_iallreduce.c
> + * Copyright (c) 2022      IBM Corporation.  All rights reserved.
This should be in the form of ` * Copyright (c) 2017-2022       IBM Corporation. All rights reserved.`

2022-03-07 23:50 UTC, gpaulsen commented
After in master, please CP to v5.0.x, v4.1.x, and v4.0.x.

2022-03-08 16:45 UTC, gpaulsen approved these changes

2022-03-08 16:57 UTC, hppritcha approved these changes

2022-03-08 18:57 UTC, gpaulsen commented
bot:aws:retest

2022-03-08 18:58 UTC, gpaulsen commented
one of the Pull Request Build Checker statuses said: 
```
> git checkout -f b77a24b303d36fa5c604c98aafa6550e62a47e38 # timeout=10
FATAL: Could not checkout b77a24b303d36fa5c604c98aafa6550e62a47e38
hudson.plugins.git.GitException: Command "git checkout -f b77a24b303d36fa5c604c98aafa6550e62a47e38" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: b77a24b303d36fa5c604c98aafa6550e62a47e38
```
So I issued the retest

2022-03-08 22:37 UTC, merged