SS11: initial ofi btl fixes
open-mpi/ompi pull request #10150
Opened 2022-03-21 20:27 UTC by hppritcha

HPE SS11 network (OFI libfabric CXI provider) requires FI_MR_ENDPOINT
be handled by the application.  Registered memory regions need to be
bound to the relevant endpoint before use.

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

2022-03-23 15:49 UTC, bwbarrett requested changes

2022-03-23 15:49 UTC, bwbarrett commented on opal/mca/btl/ofi/btl_ofi_module.c
> +	rc = fi_mr_enable(ur->ur_mr);
there's something wonky with the indenting here.

2022-03-23 15:49 UTC, bwbarrett commented on opal/mca/btl/ofi/btl_ofi_module.c
> +    if (true == btl->use_fi_mr_bind) {
if (btl->use_fi_mr_bind)

2022-03-24 16:47 UTC, hppritcha commented on opal/mca/btl/ofi/btl_ofi_component.c
> +#define MCA_BTL_OFI_REQUESTED_MR_MODE (FI_MR_ALLOCATED | FI_MR_PROV_KEY | FI_MR_VIRT_ADDR | FI_MR_ENDPOINT)
see https://github.com/ofiwg/libfabric/issues/7597
note I've added code to support FI_MR_ENDPOINT mr mode bit as part of this PR.

2022-03-24 16:50 UTC, bwbarrett commented on opal/mca/btl/ofi/btl_ofi_component.c
> +#define MCA_BTL_OFI_REQUESTED_MR_MODE (FI_MR_ALLOCATED | FI_MR_PROV_KEY | FI_MR_VIRT_ADDR | FI_MR_ENDPOINT)
Note my worry isn't just that it will disqualify providers, but may cause them to enter a more expensive path.

2022-03-24 17:37 UTC, bwbarrett commented on opal/mca/btl/ofi/btl_ofi_component.c
> +#define MCA_BTL_OFI_REQUESTED_MR_MODE (FI_MR_ALLOCATED | FI_MR_PROV_KEY | FI_MR_VIRT_ADDR | FI_MR_ENDPOINT)
Based on ofiwg/libfabric#7597, I'm happy with this change.

2022-03-29 21:44 UTC, hppritcha commented
@bwbarrett could you check this PR again?  I pushed some cleanup.  if its okay to you i'll squash and merge.

2022-03-29 21:47 UTC, bwbarrett approved these changes

2022-03-30 14:47 UTC, merged