btl/base: push operation->hdr to am_rdma_respond for queued operation
open-mpi/ompi pull request #10463
Opened 2022-06-10 02:13 UTC by wzamazon

Currently, when calling am_rdma_respond() for a queued
operation, amd_rdma_retry_operation() pass NULL for the hdr argument.

The idea is that hdr is only used for allocating operation->descriptor.
A queued operation should already have a descriptor, therefore does
not need hdr.

This missed the possibility that the allocation of descriptor
in am_rdma_respond() can fail, which will lead to the operation
to be queued without a descriptor.

This patch make retry_operation() to pass operation->hdr to
am_rdma_repsond() to address the issue.

Signed-off-by: Wei Zhang <wzam@amazon.com>

2022-06-13 12:45 UTC, wzamazon commented
@bwbarrett @hjelmn Can you review this PR? this fixed some segfault in mtt ibm/onesided tests.

2022-06-24 21:43 UTC, bwbarrett requested changes
The change makes sense.  But I think you should also add an assert in the `if (NULL == send_descriptor)` section of am_rdma_respond asserting `hdr` is not `NULL`.

2022-06-25 19:54 UTC, wzamazon commented
@bwbarrett

Thank you for the review! I added the assertion in new revision.

2022-06-28 01:54 UTC, bwbarrett approved these changes

2022-06-28 21:30 UTC, merged