C11 atomics: replace _Atomic with volatile
open-mpi/ompi pull request #10492
Opened 2022-06-21 15:01 UTC by devreal

Using the `_Atomic` type modifier leads to sequentially consistent atomic access on variables even in code paths where atomicity and ordering is not needed (`opal_thread_*` and initializations as in `opal_object_t` for example). By replacing `_Atomic` with `volatile` in the "public" interface of the C11 backend, we preserve the ability to suppress certain compiler optimizations while allowing for non-atomic accesses where not needed. All atomic accesses and ordering is done through the use of the `opal_atomic*` API throughout the code base so `_Atomic` is not needed.

My first attempt was to introduce non-atomic load/store macros in https://github.com/open-mpi/ompi/pull/10487 but the problem is pervasive and tracking down all instances of non-atomic accesses to atomic variables is tedious and likely going to miss places. I pointed out the general problem in https://github.com/open-mpi/ompi/issues/9722#issuecomment-1159557291.

The difference in performance is significant: a sequence of local `irecv - send - wait` using ob1 and btl/self shows 0.22us with current main and 0.16us with this patch for empty messages.

AFAICS, C11 `_Atomic` is designed for purely atomic accesses and not suitable for a large-scale mixed-use (performance-sensitive) model such as Open MPI.

Signed-off-by: Joseph Schuchart <schuchart@icl.utk.edu>

2022-06-21 16:46 UTC, bosilca commented
@gpaulsen you can do something like the following to get the assembly code for the function above:
`objdump -d libmpi.so | awk -v RS= '/^[[:xdigit:]]+ mca_pml_ob1_recv_req_start/'`

2022-07-13 15:44 UTC, devreal commented
I put together some code examples on [godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AB9U8lJL6yAngGVG6AMKpaAVxYMQAJg2kHAGTwGTAA5dwAjTGJvAGZSAAdUBUJbBmc3D29fROSbAUDgsJZI6K84y0xrVKECJmICdPdPHwtMKzyGGrqCAtCIqNiLWvrGzJaFYZ6gvuKBsoBKC1RXYmR2DgBSMqDkNywAag2Yxwn0JiIWPGQAOgQj7A2NAEEtmJ29zEPj06CCW/vHi9tgxdq4DkcTgR0OFUC5/jEHs9AZhVAQogx9jCXPtXMkjMYCAhiJgmOgFEcAEKAwEEACe8UwWCo%2B2MTwuV32v3251Ql2Qxl%2BBMpNPpjMwzImxFc1kOAHYqc99kruez%2BYKCNzhUjZQARfaS6UEYwAd0ICGMPL5AsEQpiCpezzpDKZ%2BwAbi5znRPlzXZartajQQtWzRS6DTKNvLAcq3X61TaNUxg5G9eGjabCcZ3QYbPQA7b7YCuVRSegLaqIHH8xqAFRMUicwRu%2BZy%2B0xvDMiC4oLAAlEklkluRtsx5XEggrDFVqiYAjIc2l4wo%2BK0K6ESsN10NtgsEi04wkLDEYzEgyqRnzYMxlP7NpKVvR0dKrkEFjxL56utXp/7OuHLxUjEequt%2BT7jpO%2ByvvEoFyjq1K6tSzzung6D6rOTAQGmJpmuWvL%2Buqv4KEOUaKsqCgALT3EwH77BoyYIUizzFou2aevQEC%2Bqq1a/vWjYaq6xEjs%2BnbdvihLEqSREPqRYGzhB06zvOFroGWy6rsg64QKyqp8TW8y8Vu%2Bw7nuB7EEeJ5tEw57oJedqPkqN53p8w72aOL5vjRX52TJo5/lsgHATBMbgcQGJQTBKbwXBjFPMhqFKAQrqYQQUrWNhmasbmmDcTWUkuT5FFUTRdHeS8DFPBwiy0JwACsvCeBwWikKgnCOPqyyrM5ZQ8KQBCaJViwANYgJIkjXDEACcABs02SGUE1eFwAAcXiyvonCSPV/XNZwvAKCAvh9Y1lWkHAsBIGgb5emQFAQJd8TXSguyGL2KWuAwg18HQaLEPtEDhNt4RBHUtKcD1l1sIIADyDC0KDx2kFgLAveICP4MSVSupg%2B0IyilSuGiYO8L8bTbau4TECDzhYNtKV4CwROLFQBjAAoABqeCYMaUMMg1PX8IIIhiOwUgyIIigqOoCO6Fw%2BgvSApjGOY5P7ZAiyoPEHQ4%2BRUNeHtbSVB09gME4LhNHoATTEUJR6DkKQCKMniy3bHS9NbAyyxUVQCF0Ixm5knsG97nSTG7/TRJ7kyO3oEzdGHswR4sCgdWsegpZg6w8FVtVbQjLUcKoS1TeRU2SPsz1GPsEBvR9LYQI4Da4IQJD/jEsv7M4V30MQrdcPMvBHVo8xDd4E3jVwE1F0tE%2ByrPNVTWt1UcJtpANU1%2Bd7QdvX9YsZ2ICAywEPEBPkPY%2BBEMQKF6ALwiiOIos3xLajbTLpDGpT8SM%2BtHB1av2351DAmx8NSoGZIXYupdy4GErtXKUtcq6dwet3Xu/dt7HWHqQYaXgprXC8EtNuC954xA0BoKaGgapxCXivNevAN4WC3oPAa389Z/zzrtNBQ9FhY1%2BqkEaQA). There are two variants: one using `_Atomic` and one using `volatile`. One function, `fadd_[atomic|volatile]` does what the opal wrappers do: check a global variable for thread support and fall back to non-atomic operations if threads are disabled. The second function, `set[a|v]` non-atomically sets a member in a structure, something typically done during structure initialization. 

In both cases, using the `_Atomic` prefix results in atomicity in the non-atomic code paths.

2022-07-13 16:42 UTC, bosilca approved these changes

2022-07-17 11:44 UTC, jsquyres commented
@bwbarrett Could you review?

2022-07-18 13:15 UTC, bwbarrett requested changes
This feels like yet another hack around a fundamentally broken design.  We're intentionally breaking the interface for the C11 atomics, which will bite us later.  I think we need to step back and make a broader decision about our atomics design, rather than continue hacking at the interface using poorly defined semantics (ie, volatile).

2022-07-18 14:14 UTC, devreal commented
I agree that this is a band-aid but I didn't feel comfortable proposing a complete overhaul. If we want to go down that road we might want to look at other places: the Linux kernel for example uses a custom struct around an integer [1] to prevent direct load/store access and provides macros for initialization and atomic / non-atomic access [2]. Interestingly, the kernel is still using `volatile` and not `_Atomic`, despite articles a few years back talking about possibly using C11 atomics [3]. There is an overview of the atomics infrastructure in [4].

By using a custom structure around  an `_Atomic` variable and encapsulating all accesses in macros/inline functions we can use `atomic_store_explicit` with `memory_order_relaxed` for non-atomic loads and stores. It would require touching a lot of code though. Otherwise `volatile` is the only way I see to prevent compiler optimizations that would break existing code and prevent atomic operations in places where they are not needed. Maybe someone has other ideas? 


[1] https://github.com/torvalds/linux/blob/master/include/linux/types.h#L72
[2] https://github.com/torvalds/linux/blob/master/include/asm-generic/rwonce.h#L44
[3] https://lwn.net/Articles/691128/
[4] https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0124r5.html

2022-07-18 15:04 UTC, devreal commented
MPICH seems to be using a similar approach: https://github.com/pmodels/mpich/blob/main/src/mpl/include/mpl_atomic_c11.h (from my limited understanding of their code base)

2022-08-15 13:41 UTC, gpaulsen commented
On ppc64le, objdump of mca_pml_ob1.so gave me:
```
0000000000005220 <00000018.plt_call.mca_pml_ob1_recv_req_start>:
    5220:       18 00 41 f8     std     r2,24(r1)
    5224:       90 88 82 e9     ld      r12,-30576(r2)
    5228:       a6 03 89 7d     mtctr   r12
    522c:       20 04 80 4e     bctr
        ...
```

And then I've uploaded the full disassembly to: 
<script src="https://gist.github.com/gpaulsen/8d96a9e9dc8c17e803a56e3da7c122ac.js"></script>

2022-08-16 15:35 UTC, closed without merging