Atomics: default to GCC builtin atomics and use C11 _Atomic as fall-back
open-mpi/ompi pull request #10613
Opened 2022-07-26 22:34 UTC by devreal

As per the discussion in https://github.com/open-mpi/ompi/pull/10492 (https://github.com/open-mpi/ompi/pull/10492#issuecomment-1189087429) we want to replace the C11 `_Atomic` variables with a custom wrapper around basic atomic types. However, this requires significant changes throughout the code base to wrap direct assignment and initialization in macros. We may not want to backport this to 5.0.x at such a late stage. Instead this PR provides some fixes for the GCC builtin atomics (`__atomic`) and makes them the default, with C11 atomics as a fallback. This can then be backported to 5.0.x before attempting the larger changes in `main`.

The underlying problem is that C11 atomics require us to annotate atomic variables with `_Atomic` that then makes direct assignment sequentially consistent, which in turn make initialization costly and defeats the purpose of the `OPAL_THREAD_*` macros that try to avoid atomic operations if possible. As an alternative, https://github.com/open-mpi/ompi/pull/10492 removes the `_Atomic` annotation of variables and adds casts to the atomic functions, which is a hack.

Signed-off-by: Joseph Schuchart <schuchart@icl.utk.edu>

2022-08-24 16:32 UTC, bwbarrett commented
bot:recheck

2022-08-24 16:41 UTC, bwbarrett requested changes

2022-08-24 16:41 UTC, bwbarrett commented on opal/include/opal/sys/gcc_builtin/atomic.h
> +#if defined(PLATFORM_ARCH_X86_64) && defined(PLATFORM_COMPILER_GNU) && __GNUC__ < 8
This should really be two commits (changing the default, and then changing the builtn code).  I'm happy with the platform compiler change, but why are we changing the version of GCC that has the busted MB?

2022-08-24 16:41 UTC, bwbarrett commented on opal/include/opal/sys/gcc_builtin/atomic.h
> +    if (OPAL_ATOMIC_LOCK_UNLOCKED == value) {
This either feels unnecessary or incomplete.  Either we need an atomic set here in both cases or neither case.

2022-08-24 16:41 UTC, bwbarrett commented on opal/include/opal/sys/gcc_builtin/atomic.h
> +    bool ret = __atomic_test_and_set(&lock, OPAL_ATOMIC_LOCK_LOCKED,
This all should be in its own commit with its own justification.  This code was used in production prior to the 5.0 series, so it feels like (without justification in a commit message or comment) this is changing things to change things.

2022-08-25 15:00 UTC, awlauria commented
/azp run

2022-08-25 15:01 UTC, awlauria commented
bot:aws:retest

2022-08-26 20:40 UTC, devreal commented
Replaced by https://github.com/open-mpi/ompi/pull/10721, closing

2022-08-26 20:40 UTC, closed without merging