java: catch exceptions if we fail to load mpi_java
open-mpi/ompi pull request #10697
Opened 2022-08-20 17:41 UTC by hppritcha

library.

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

2022-08-20 17:42 UTC, hppritcha commented
a step along the way to retaining ease of use with prrte for java apps

2022-08-21 23:31 UTC, kawashima-fj requested changes
@hppritcha Just a question. How the behavior is changed? Only the messsage change? Exiting cleanly?

2022-08-21 23:31 UTC, kawashima-fj commented on ompi/mpi/java/java/MPI.java
> +                    System.err.println("mpi java lib failed to load" + e  + "\n") ;
Please insert a space of something before the Java exception message.

```suggestion
                    System.err.println("mpi java lib failed to load: " + e  + "\n") ;
```

2022-08-22 14:29 UTC, hppritcha commented
@kawashima-fj check now, hopefully i got the tabs right!

2022-08-22 14:57 UTC, kawashima-fj commented on ompi/mpi/java/java/MPI.java
> +                }
This line still has space-indentation.

2022-08-22 15:11 UTC, hppritcha commented on ompi/mpi/java/java/MPI.java
> +                }
okay i think that fixed it.

2022-08-22 15:12 UTC, hppritcha commented
@kawashima-fj  i think line 210 is fixed now

2022-08-22 23:07 UTC, kawashima-fj approved these changes

2022-08-22 23:57 UTC, merged