ofi-common-dso: allow this only if other ofi comps
open-mpi/ompi pull request #10710
Opened 2022-08-24 01:51 UTC by hppritcha

are also on the enable-dso-mca list

with this patch, if one configures with --enable-mca-dso=common-ofi

but not also ofi-btl or/and ofi-mtl they get a configure failure with
this sort of message:

configure: error: ofi-btl must be included on the --enable-mca-dso list if common-ofi is on this list

related to #9451

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

2022-08-24 01:51 UTC, hppritcha commented
this same problem will show up with UCX. I'll open a comparable PR for UCX.

2022-08-24 03:40 UTC, bwbarrett requested changes

2022-08-24 03:40 UTC, bwbarrett commented on ompi/mca/mtl/ofi/configure.m4
> +    MCA_COMPONENT_COMPILE_MODE("opal", "common", "ofi", common_ofi_compile_mode)
I don't think we want to call `MCA_COMPONENT_COMPILE_MODE` as it exists today from here.  Two reasons: first, it's going to print out an `AC_MSG_CHECKING` that will be very confusing.  Second, this code almost certainly will be copied around (you already call out UCX, but any component that depends on a common component needs such a check), and there's an implicit assumption that neither the calling component nor the common component override the `MCA_COMPONENT_COMPILE_MODE` option.

I think both problems are solvable relatively easily, but won't have time to post a patch until tomorrow night.

2022-09-06 18:25 UTC, jsquyres commented
I think #10767 will replace this PR.

2022-09-07 14:20 UTC, closed without merging