Avoid calling twice into opal_mutex_lock() in ompi_mpi_instance_init()
open-mpi/ompi pull request #10720
Opened 2022-08-25 21:50 UTC by janciesko

Avoid deadlock by calling opal_mutex_lock twice on same thread. Since ompi_mpi_instance_init_common is called only from ompi_mpi_instance_init, this refactor should be otherwise equivalent.

2022-08-25 23:33 UTC, devreal commented
ok to test

2022-08-25 23:38 UTC, devreal requested changes

2022-08-25 23:38 UTC, devreal commented on ompi/instance/instance.c
> -            opal_mutex_unlock (&instance_lock);
Removing that unlock seems incorrect

2022-08-26 17:15 UTC, janciesko commented on ompi/instance/instance.c
> -            opal_mutex_unlock (&instance_lock);
Yes. Updated.

2022-08-26 17:59 UTC, devreal commented
I'm not sure if this is connected to your patch but there seem to be instances where the `instance_lock` is released twice:

- https://github.com/open-mpi/ompi/blob/4f604e7ecaead3bd51002b580714bf1688756168/ompi/instance/instance.c#L1050
- https://github.com/open-mpi/ompi/blob/4f604e7ecaead3bd51002b580714bf1688756168/ompi/instance/instance.c#L815

`instance_lock` is a recursive lock and the title makes it sound like you're removing lock calls...

2022-08-26 19:14 UTC, janciesko commented
Good point, the PR might se side stepping another issue then. It might be that the recursive lock does not work. Currently, this sequence deadlocks. 
```
opal_mutex_lock(...)
opal_mutex_lock(...)
```

2022-08-30 19:08 UTC, gpaulsen commented
@janciesko What's your plan with this PR?

2022-08-30 20:06 UTC, janciesko commented
This error is specific to the Qthreads ULT support - currently Qthreads does not support recursive mutex. The correct fix seems to be to add recursive mutex support to Qthreads. This would avoid the deadlock in ompi for that sequence of lock acquisitions.

2022-08-30 20:07 UTC, janciesko commented
We can close this PR and I will open a new PR with the updated calls to Qthreads recursive locking.

2022-08-30 20:11 UTC, closed without merging