Coll han update file reading 5.0.x
open-mpi/ompi pull request #11043
Opened 2022-11-08 09:23 UTC by FlorentGermain-Bull

Rebase of #10828 + #10456 + #10458  on v5.0.x branch

2022-11-08 15:58 UTC, awlauria commented
ok to test

2022-11-08 16:54 UTC, devreal requested changes
Can you please include cherry-picks of https://github.com/open-mpi/ompi/pull/10983 and https://github.com/open-mpi/ompi/pull/10992 here since they are fixing issues in these changes?

2022-11-08 16:54 UTC, devreal commented on ompi/mca/coll/han/coll_han_component.c
> +const char* mca_coll_han_topo_lvl_to_str(TOPO_LVL_T topo_lvl_id)
I realize t hat this breaks the common naming scheme. It should be `ompi_coll_han_topo_lvl_to_str`. Given that this has been merged into main already this (and other occurrences) should be fixed in a separate PR.

2022-11-08 22:04 UTC, bosilca approved these changes

2022-11-15 07:54 UTC, FlorentGermain-Bull commented
> Can you please include cherry-picks of #10983 and #10992 here since they are fixing issues in these changes?

done
+ rebase on v5.0.x

2022-11-15 14:53 UTC, jsquyres commented
bot:ibm:retest

2022-11-15 19:01 UTC, devreal approved these changes

2022-11-22 15:26 UTC, merged