opal/convertor: Use regular memcpy when detecting Unified memory
open-mpi/ompi pull request #11048
Opened 2022-11-08 19:00 UTC by wckzhang

During some testing, cuMemcpyAsync was failing on managed memory. Unified memory is able to accept regular memcpy so switch to that instead.

Signed-off-by: William Zhang <wilzhang@amazon.com>

2022-11-09 15:40 UTC, bosilca reviewed
What is the impact of this change performance-wise ? I think it would be beneficial to understand why `cuMemcpyAsync` was failing on managed memory ?

2022-11-09 17:27 UTC, bwbarrett requested changes
At the very least, this needs a comment on why this is ok / safe / not performance crazy.

But it also needs George's questions answered, so tagging as "request changes" until that gets sorted out.

2022-11-09 17:55 UTC, wckzhang commented
One of the main benefits from the Unified memory model is to simplify the coding by allowing regular memcpy usage. Memory is visible from both CPU and GPU. There doesn't seem to be good documentation describing the performance impact of using cuda memcpy API vs using regular memcpy API but it looks like it's typical to not use the cuda memcpy API when using managed memory.

From my own experiments, there is an increase in performance when using memcpy on smaller message sizes and a decrease in performance at larger message sizes in the simplest of examples:

```
With regular memcpy()
ubuntu@ip-172-31-15-68:~/ompi$ ~/install/bin/mpirun -np 2 --mca pml cm  ~/osucuinstall/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency MD MD
# OSU MPI-CUDA Latency Test v6.1
# Send Buffer on MANAGED (MD) and Receive Buffer on MANAGED (MD)
# Size          Latency (us)
0                       3.35
1                      12.53
2                      13.13
4                      12.61
8                      12.64
16                     13.01
32                     12.78
64                     13.22
128                    13.31
256                    13.21
512                    16.48
1024                   16.59
2048                   17.20
4096                   23.47
8192                   39.44
16384                  66.67
32768                 343.82
65536                 555.27
131072                784.71
262144               1221.20
524288               1737.18
1048576              2131.31
2097152              3024.03
4194304              5770.77
```

```
With cuMemcpyAsync
ubuntu@ip-172-31-15-68:~/ompi$ ~/install/bin/mpirun -np 2 --mca pml cm  ~/osucuinstall/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency MD MD
# OSU MPI-CUDA Latency Test v6.1
# Send Buffer on MANAGED (MD) and Receive Buffer on MANAGED (MD)
# Size          Latency (us)
0                       3.33
1                      41.07
2                      40.76
4                      40.95
8                      40.69
16                     41.33
32                     41.20
64                     41.23
128                    41.12
256                    41.43
512                    41.42
1024                   42.09
2048                   45.11
4096                   48.95
8192                   52.23
16384                  58.69
32768                  70.26
65536                  94.05
131072                141.30
262144                236.58
524288                426.56
1048576               766.18
2097152              1281.95
4194304              2367.56
```

So using memcpy is safe, the performance is not clear from the documentation in the cuda toolkit documentation/forums, and it is not clear why cuMemcpyAsync would ever fail on managed memory (I don't know if I can answer this one by myself. The Async copy in question is followed by an immediate synchronization so I don't think that would be the issue). I tried asking @Akshay-Venkatesh if he would know why it would fail with error (1):

```
CUDA_ERROR_INVALID_VALUE = 1
This indicates that one or more of the parameters passed to the API call is not within an acceptable range of values.
```

but I haven't gotten a response yet. I'd also like to know more about the performance differences between using memcpy and cuda API memcpy as well.

2022-11-09 18:44 UTC, bwbarrett commented
It looks like the OSU benchmark is allocating managed memory.  What happens if the memory is not managed memory, but allocated explicitly with cudaMalloc()?

2022-11-09 18:59 UTC, bosilca commented
If the copy is d2h or h2d, both calls (cuMemcpyAsync and memcpy) will go once over the PCI bus, so we can assume the performance of the operation will be capped by this. However, if the copy is d2d, then memcpy will be the wrong choice because the copy operation will not benefit from the device memory or NVLink transfers (where the bandwidth is order of magnitude higher than the PCI bus, aka 900GB/s for a V100 compared with 64GB/s for PCIe4 and 128GB/s for PCI5).

We also need to take in account the kernel submission time. Indeed, from your results you can see that memcpy was significantly faster for small sizes ( below 64k) but once that limit is overcome cuMemcpy was way more efficient. Thus, I don't think this PR is yet the right approach.

2022-11-09 21:03 UTC, edgargabriel commented
my $0.02 on this topic:

I think calling the allocator copy function would probably still be the right approach, for two reasons: 
1. I don't think we can make the general statement for all (current or future) accelerator components that using memcpy for unified memory is the right approach
2. the allocator copy function can do whatever is optimal for that memory type (memcpy vs. device specific copy function, synchronization of the memory if required, etc.). Not sure if we need/want to amend the interfaces with some flags to indicate unified vs device memory or whether we want the code to perform the memory type check internally.

2022-11-09 21:08 UTC, bwbarrett commented
> > It looks like the OSU benchmark is allocating managed memory. What happens if the memory is not managed memory, but allocated explicitly with cudaMalloc()?
> 
> I don't understand the question, memory allocated with cudaMalloc cannot be copied using memcpy.

Maybe I'm misunderstanding when UNIFIED is set, but CUDA docs seem to indicate that memory allocated with cudaMalloc and later registered is considered unified memory.  Will we set UNIFIED in that case?

2022-11-09 23:15 UTC, wckzhang commented
> Maybe I'm misunderstanding when UNIFIED is set, but CUDA docs seem to indicate that memory allocated with cudaMalloc and later registered is considered unified memory. Will we set UNIFIED in that case?

Can you share a link to that part of the CUDA doc? I can't find it from searching myself. It doesn't appear like the cuda API can pin device memory and the host pinned memory is identified as host memory as far as I can tell.

> I don't think we can make the general statement for all (current or future) accelerator components that using memcpy for unified memory is the right approach
the allocator copy function can do whatever is optimal for that memory type (memcpy vs. device specific copy function, synchronization of the memory if required, etc.). Not sure if we need/want to amend the interfaces with some flags to indicate unified vs device memory or whether we want the code to perform the memory type check internally.

This is a good idea I think, passing through whether the memory is unified memory to the API sounds like the right per component behavior.

2022-11-17 02:51 UTC, Akshay-Venkatesh commented
> There doesn't seem to be good documentation describing the performance impact of using cuda memcpy API vs using regular memcpy API but it looks like it's typical to not use the cuda memcpy API when using managed memory.

Sorry for seeing this late. Performance of moving managed memory depends on where the pages of the managed memory allocation resides. Where the pages reside is dependent on runtime heuristics but commonly pages are likely located where last touched. If it's the case that the benchmark just allocated memory and then immediately called MPI operations then calling memcpy would see good performance. On the other hand, the memory region had pages migrated to the device because a compute kernel accessed it, then calling memcpy on the same region would require the pages to migrate over to CPU and then the actual copy is performed and performance would be worse off compared to copy engines (through cuMemcpyAsync) directly trying to copy from those pages. There is no perfect solution here just yet where a given copy scheme results in no page migration and yet you get the best possible copy performance. One assumption we make is that pages are more likely to remain in device because they're likely to be used by kernels - so this approach always uses copy engines to move memory. Another alternative is to expect user to provide [preferred location hints](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__UNIFIED.html#group__CUDA__UNIFIED_1g1c92408a7d0d8875e19b1a58af56f67d) and the runtime queries this and chooses an appropriate copy mechanism.

@bwbarrett 
> Maybe I'm misunderstanding when UNIFIED is set, but CUDA docs seem to indicate that memory allocated with cudaMalloc and later registered is considered unified memory. Will we set UNIFIED in that case?

Strictly speaking unified memory is memory allocated through cudaMallocManaged. That said it is possible to allocate host memory and map it to cuda address space (I believe you're referring to DEVICEMAP mode [here](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MEM.html#group__CUDA__MEM_1gf0a9fe11544326dabd743b7aa6b54223)) but this is generally a slow path.

I agree with @edgargabriel on leaving it to allocator copy function for the general case even if micro-benchmarks may not show optimal performance (Also, I think OSU mb has an option to have kernels touch memory cuda managed memory before MPI transfers but I don't know if the memory is touched before iteration).

2022-11-17 02:52 UTC, Akshay-Venkatesh commented on opal/datatype/opal_convertor.c
> +    if (!(convertor->flags & CONVERTOR_ACCELERATOR) || (convertor->flags & CONVERTOR_ACCELERATOR_UNIFIED)) {
@wckzhang Not in favor of this change.

2022-11-21 22:28 UTC, wckzhang commented
Closing this PR, will come back with a different change

2022-11-21 22:28 UTC, closed without merging