coll/ucc: add support for gather(v), scatterv, reduce_scatter
open-mpi/ompi pull request #11091
Opened 2022-11-18 12:27 UTC by Sergei-Lebedev

Add support for more collectives in coll ucc: gather, gatherv, reduce_scatter, reduce_scatter_block, scatterv
Signed-off-by: Sergey Lebedev <sergeyle@nvidia.com>

2022-11-28 15:05 UTC, bureddy approved these changes

2022-11-28 15:15 UTC, edgargabriel commented
a small question just for clarification: it seems like this commit adds support for scatterv, but not for scatter, is this in purpose? (the commit does add however support for gather and gatherv)

2022-11-29 06:43 UTC, Sergei-Lebedev commented
> a small question just for clarification: it seems like this commit adds support for scatterv, but not for scatter, is this on purpose? (the commit does add e.g. support for gather and gatherv)

yes, in UCC we don't have generic scatter implementation so far. Only device specific TLs (NCCL, RCCL, CUDA) supports it.

2022-11-29 06:47 UTC, vspetrov requested changes

2022-11-29 06:47 UTC, vspetrov commented on ompi/mca/coll/ucc/coll_ucc_gatherv.c
> +                                         ucc_module->previous_igather_module);
previous_igather**V**_module

2022-11-29 06:47 UTC, vspetrov commented on ompi/mca/coll/ucc/coll_ucc_reduce_scatter.c
> +        /* TODO: UCC defines inplace differently:
UCC_VERBOSE(5, "fallback ... ") ?

2022-11-29 06:47 UTC, vspetrov commented on ompi/mca/coll/ucc/coll_ucc_reduce_scatter.c
> +    int total_count, i;
make total_count size_t

2022-11-29 06:47 UTC, vspetrov commented on ompi/mca/coll/ucc/coll_ucc_reduce_scatter_block.c
> +            .count    = rcount * comm_size,
rcount * comm_size -> ((size_t)rcount) * comm_size to avoid potential INT overrun

2022-11-29 09:30 UTC, devreal commented
>> a small question just for clarification: it seems like this commit adds support for scatterv, but not for scatter, is this on purpose? (the commit does add e.g. support for gather and gatherv)
>
> yes, in UCC we don't have generic scatter implementation so far. Only device specific TLs (NCCL, RCCL, CUDA) supports it.

Scatter is a specialization of scatterv. Why not implement the former in terms of the latter?

2022-11-30 07:18 UTC, vspetrov approved these changes

2022-11-30 14:53 UTC, janjust commented
We're holding off until scater is added as a commit, then I'll merge

2022-12-01 14:22 UTC, Sergei-Lebedev commented
@edgargabriel @devreal added scatter in last commit

2022-12-01 14:31 UTC, edgargabriel commented
> @edgargabriel @devreal added scatter in last commit

excellent, thank you very much!

2022-12-01 18:59 UTC, merged