advance prrte and pmix shas
open-mpi/ompi pull request #11183
Opened 2022-12-08 22:21 UTC by hppritcha

openpmix to  a789c937224a84eadd6aa85b424cb59538794e7e 
prrte to 82811e9068ec786f3283bbd085b2a8b0ebed6f9a

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

2022-12-08 22:21 UTC, hppritcha commented
discussions at PMIx webex today motivated this.

2022-12-12 04:43 UTC, bwbarrett requested changes
Austen has been including the list of commits in the change; I'm not sure sure if he's doing that manually or with a script, but we should do that here.

2022-12-12 16:21 UTC, hppritcha commented
done

2022-12-12 17:07 UTC, bwbarrett approved these changes

2022-12-13 16:16 UTC, merged