WIP: MRecv didn't generate SSend ACK's
open-mpi/ompi pull request #11327
Opened 2023-01-18 22:21 UTC by lrbison

This commit refactors the generation of 0-byte ACKs from the body of ompi_mtl_ofi_recv_callback so that it can be used by the ompi_mtl_ofi_mrecv_callback function as well.

Signed-off-by: Luke Robison <lrbison@amazon.com>

---

Found this issue in mpi4py testing framework.  Previously calls to MRecv wouldn't generate a maching ACK for SSend, and progress would deadlock.

Currently this change fixes the deadlock, but sometimes we seem to be matching the wrong message so validation fails, and we also crash during Finalize:

```
#3  0x00007fe3a0dc7ac2 in __assert_fail () from /lib64/libc.so.6
#4  0x00007fe3935cb29b in ofi_buf_free (buf=0x7fe3800a1e40) at ./include/ofi_mem.h:422
#5  0x00007fe3935cb8ed in rxr_release_rx_entry (ep=0x21c5c80, rx_entry=0x7fe3800a1e40) at ./prov/efa/src/rxr/rxr.h:554
#6  0x00007fe3935cd8b6 in rxr_ep_free_res (rxr_ep=0x21c5c80) at prov/efa/src/rxr/rxr_ep.c:565
#7  0x00007fe3935ce5b3 in rxr_ep_close (fid=0x21c5c80) at prov/efa/src/rxr/rxr_ep.c:775
#8  0x00007fe393eea930 in fi_close (fid=0x21c5c80) at /fsx/lrbison/installs/libfabric/include/rdma/fabric.h:621
#9  0x00007fe393eeea4d in ompi_mtl_ofi_finalize (mtl=0x7fe39433c080 <ompi_mtl_ofi>) at mtl_ofi_component.c:1155
```

2023-01-19 03:21 UTC, lrbison commented
Looks like the Pull Request Build Checker failed with:
> `/home/ubuntu/workspace/open-mpi.build.distcheck: No space left on device`

2023-01-19 16:00 UTC, lrbison commented
Originally I had some segfaults while testing this PR, but after re-basing it on top of my updated MPI_Cancel fix for OFI MTL (#11324) , the problem is resolved, and I believe that was the root cause.

This PR can be merged independently of the MPI_Cancel fix, as it does prevent deadlock on SSends.

Ready for main?

2023-01-19 16:06 UTC, lrbison commented
Updated commit message and title to make it clear this only affects MTL/OFI

2023-01-24 00:23 UTC, bwbarrett requested changes
Please change the commit title.  It's not that you're not generating SSend acks in mrecv, it's that you are refactoring code to allow the ack generation to be used elsewhere.  One is a code cleanup, the other is a protocol change.  Big difference.

2023-01-24 00:23 UTC, bwbarrett commented on ompi/mca/mtl/ofi/mtl_ofi.h
> +__opal_attribute_always_inline__ static inline int
This function shouldn't be always-inlined.  Yes, I know someone got this entire component wrong before, but we don't need to propogate the badness.

2023-01-24 00:23 UTC, bwbarrett commented on ompi/mca/mtl/ofi/mtl_ofi.h
There should be a small comment header describing what this function does, when to call it, any non obvious assumptions.

2023-02-01 22:57 UTC, wckzhang approved these changes

2023-02-01 22:57 UTC, merged