Distances
open-mpi/ompi pull request #11565
Opened 2023-04-05 23:32 UTC by amirshehataornl

mtl/ofi: NIC selection update

The existing code in compare_cpusets assumed that some non_io ancestor of a
PCI object should intersect with the cpuset of the proc. However, this is
not true. There is a case where the non IO ancestor can be an L3. If there
exists two L3s on the same NUMA and the process is bound to one L3, but
the PCI object is connected to the other L3, then compare_cpusets() will
return false.

A better way to determine the optimal interface is by finding the
distances of the interfaces from the current process. Then find out which
of these interfaces is nearest the process and select it.

Use the PMIx distance generation for this purpose.

Move away from using deprecated PMIX Macros and use the functions directly.
Avoid some compilation issues due to an error in PMIX code

Signed-off-by: Amir Shehata <shehataa@ornl.gov>

2023-04-10 19:08 UTC, bwbarrett requested changes
Neither of these patches are unique to mtl/ofi behaviors; they'll change the btl as well.  Please update the prefix to be less specific (like just `ofi:`).

2023-04-17 19:22 UTC, janjust commented
@amirshehataornl can you separate out pmix/prrte changes?

2023-04-25 12:35 UTC, awlauria commented
Is this ready to go?

2023-04-25 14:58 UTC, naughtont3 commented
yes, this is ready

2023-04-28 20:03 UTC, naughtont3 commented
@bwbarrett Can you rereview/approve.  The changes were made to reflect your feedback.  Thanks.

2023-04-28 20:27 UTC, bwbarrett approved these changes

2023-05-02 14:45 UTC, naughtont3 commented
@awlauria this is ready to merge

2023-05-02 14:46 UTC, merged