docs: update list of deprecated/removed functions
open-mpi/ompi pull request #11825
Opened 2023-07-14 14:30 UTC by edgargabriel

This commit address issue #10099

Update documentation with the list of depreacted functions in MPI 2.2 and MPI-4.0. Add some examples and explanation on how to convert code from the deprecated interfaces to the new ones.

Add a new section on ABI compatibility to Open MPI 4.1

2023-07-14 14:44 UTC, edgargabriel commented
@jsquyres the main issue in this pr that is still missing in my opinion is to document the changes that have occurred in the fortran interface. I do recall that there was some discussion about it, but I do not remember the details, so I might need some help (mentioned this explicitly in the file abi-compatibility.rst).

2023-07-23 21:48 UTC, jsquyres requested changes

2023-07-23 21:48 UTC, jsquyres commented on docs/building-apps/abi-compatibility.rst
> +Open MPI 4.1 might not execute correctly with Open MPI 5.0.
```suggestion
Open MPI v4.x might not execute correctly with Open MPI 5.0.
```

2023-07-23 21:48 UTC, jsquyres commented on docs/building-apps/abi-compatibility.rst
> +5.0 without having to recompile the application.
The ABI guarantees go all the way back to v4.0.0 -- not just v4.1.x.  I.e., the "last major release" is 4, not 4.1.

```suggestion
The Open MPI |ompi_series| series maintains Application Binary Interface (ABI)
compatibility for the C MPI bindings to the last major Open MPI release. Specifically, an
application compiled with Open MPI v4.x can be executed with Open MPI
|ompi_series| without having to recompile the application.

.. important:: ABI is maintained for *most* of the Fortran MPI bindings, too -- see below for additional information.
```

2023-07-24 13:44 UTC, edgargabriel commented on docs/building-apps/deprecation-warnings.rst
> +`MPI_Keyval_create` has been deprecated and replaced by
I have incorporate this comment, but without merging the suggestions, since I had to apply this fix to many other locations.

2023-07-24 14:57 UTC, jsquyres approved these changes

2023-07-24 16:51 UTC, merged