Big Count: first pass for coll framework bc
open-mpi/ompi pull request #12539
Opened 2024-05-09 21:19 UTC by hppritcha

This commit adds only those functions which make use of C integer promotion. So none of the 'v,w' and reduce_scatter related methods are added in this PR.

Related to #12336
Pieces of #12478 were taken out to make this PR.

2024-05-09 22:26 UTC, devreal requested changes
Some comments: I prefer `%zu` over `%lu` for `size_t` (I stopped marking them at some point) and there is a place that can be simplified with the `size_t` conversion.

2024-05-09 22:26 UTC, devreal commented on ompi/mca/coll/base/coll_base_scatter.c
> +    int line = -1, rank, vrank, size, err, packed_size;
We should probably get rid of the `packed_sizet` below and make `packed_size` `size_t`.

2024-05-09 22:47 UTC, jsquyres commented
> Some comments: I prefer `%zu` over `%lu` for `size_t` (I stopped marking them at some point) and there is a place that can be simplified with the `size_t` conversion.

Is there a reason to not use `PRIsize_t`?  I thought that was guaranteed to be the Right Thing.

https://github.com/open-mpi/ompi/wiki/PrintfCodes

2024-05-09 22:56 UTC, devreal commented
`%zu` is the format specifier for `size_t`, since C99 :) much more readable than the macro string concatenation  https://en.cppreference.com/w/c/io/fprintf

2024-05-13 15:35 UTC, hppritcha commented on ompi/mca/coll/base/coll_base_allreduce.c
> +    if ((count % (size * segcount) >= (size_t) size) &&
I think that would be confusing since size is the number of processes in the communicator.

2024-05-13 15:41 UTC, hppritcha commented on ompi/mca/coll/adapt/coll_adapt_ireduce.c
> +                                      "[%d]: In ireduce, create irecv for seg %d, peer %d, recv_count %lu, inbuf %p tag %d\n",
fixed

2024-05-13 15:42 UTC, hppritcha commented on ompi/mca/coll/base/coll_base_allreduce.c
> +                 "coll:base:allreduce_intra_ring rank %d, count %lu", rank, count));
fixed

2024-05-13 15:42 UTC, hppritcha commented on ompi/mca/coll/base/coll_base_allreduce.c
> +                 "coll:base:allreduce_intra_ring_segmented rank %d, count %lu", rank, count));
fixed

2024-05-13 15:42 UTC, hppritcha commented on ompi/mca/coll/base/coll_base_allreduce.c
> +            OPAL_OUTPUT((ompi_coll_base_framework.framework_output, "coll:base:allreduce_ring_segmented rank %d/%d, count %lu, switching to regular ring", rank, size, count));
fixed

2024-05-13 15:46 UTC, hppritcha commented on ompi/mca/coll/base/coll_base_allreduce.c
> +        if (count < (size_t) (size * segcount)) {
fixed

2024-05-13 22:13 UTC, devreal approved these changes
Thanks @hppritcha! My picky clang didn't find any warnings related to these changes.

2024-05-20 19:54 UTC, merged