Fix some compiler warnings
open-mpi/ompi pull request #12685
Opened 2024-07-18 12:39 UTC by devreal

Random selection of compiler warnings found with Clang 17. 

The warnings addressed here:

```
pialltoallw_f.c: In function ‘ompi_ialltoallw_f’:
pialltoallw_f.c:110:12: warning: ‘c_sdispls’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     c_ierr = PMPI_Ialltoallw(sendbuf,
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
                              OMPI_ARRAY_NAME_CONVERT(sendcounts),
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                              OMPI_ARRAY_NAME_CONVERT(sdispls),
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                              c_sendtypes,
                              ~~~~~~~~~~~~
                              recvbuf,
                              ~~~~~~~~
                              OMPI_ARRAY_NAME_CONVERT(recvcounts),
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                              OMPI_ARRAY_NAME_CONVERT(rdispls),
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                              c_recvtypes, c_comm, &c_request);
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pialltoallw_f.c:110:12: warning: ‘c_sendcounts’ may be used uninitialized in this function [-Wmaybe-uninitialized]
```

```
../../../../ompi/mca/coll/base/coll_base_allreduce.c: In function ‘ompi_coll_base_allreduce_intra_allgather_reduce’:
../../../../ompi/mca/coll/base/coll_base_allreduce.c:1284:9: warning: unused variable ‘rank’ [-Wunused-variable]
     int rank = ompi_comm_rank(comm);
         ^~~~
```

```
../../../../../opal/mca/smsc/xpmem/smsc_xpmem_component.c: In function ‘mca_smsc_xpmem_component_query’:
../../../../../opal/mca/smsc/xpmem/smsc_xpmem_component.c:119:19: warning: variable ‘low’ set but not used [-Wunused-but-set-variable]
         uintptr_t low, high;
                   ^~~
```

2024-07-18 14:51 UTC, bosilca approved these changes

2024-07-18 14:51 UTC, bosilca reviewed
The commits are not signed. Don't merge before fixing this.

2024-07-18 14:51 UTC, bosilca requested changes
sign the commits

2024-07-18 15:23 UTC, devreal commented
They are signed with a `Signed-off-by` line but no cryptographically. I can try to get me the verified tag but I don't think we have required that in the past

2024-07-18 15:32 UTC, bosilca commented
I thought we did, but after checking the last set of commits it appears we haven't. Most of the regular contributors are either "Verified" or nothing. But somehow you are specifically marked as "Unverified".

2024-08-10 11:56 UTC, jsquyres approved these changes
@bosilca You have a negative review based on asking @devreal to sign his commits. Can you change that to a positive review?

Thanks!

2024-08-10 15:32 UTC, bosilca approved these changes

2024-08-10 15:32 UTC, merged