Avoiding building support for any accelerator-based modules without accelerators
open-mpi/ompi pull request #12775
Opened 2024-08-22 14:44 UTC by bosilca

Don't build any module used by accelerator support (SMSC, BTL, rcache, coll) if the accelerator support is not enabled or not detected. This PR now encompass support for CUDA, ROCM and ze.

2024-08-22 14:48 UTC, hppritcha submitted a review, later dismissed

2026-02-07 21:41 UTC, hppritcha commented
@edgargabriel could you review this PR?

2026-02-09 14:22 UTC, edgargabriel commented
I would recommend closing this PR unmerged. There is no direct dependency between smcuda and cuda anymore, it is generalized to use the accelerator framework API. The PR might have made sense in 5.0.x, but not in current main and 6.0.x

2026-02-09 16:46 UTC, bosilca commented
That was not the only goal of this PR. The smcuda BTL, when available because it was built, will always be loaded which results in the creation of the backend file and the registration of the progress function, a totally unnecessary wastage of resources and time.

Users can disable the BTL manually, but it is annoying to do so. Moreover, in most cases this will have absolutely no impact, if accelerators are available this BTL will be build and will have exactly the same signature impact as today.

2026-02-09 17:26 UTC, edgargabriel commented
but then lets do it differently such that if the user sets something like no-acceletors, we avoid compiling 

- btl/smcuda
- smsc/accelerator
- coll/acceleratorr
- maybe rcache/rgpus, gpusm

This Pr is definitley not good, because you can use smcuda also with rocm, so automatically disabling smcuda just because you did not find cuda is not the correct solution

2026-02-09 19:19 UTC, bosilca commented
1. As I said in my comment I did it for CUDA and I expect others will extend it for their accelerator (**hint**)
2. It would be nice to extend it everywhere, but not necessary. For the other components we could save the module load, but little else (no progress and no backend file).

2026-02-28 14:34 UTC, edgargabriel requested changes
I am conceptually fine with the solution, but I do have two change requests:

 - could you please add the top of the configure.m4 files a brief explanation why it is sufficient to check only for cuda and what are the assumptions ? (e.g. you assume that the opal/accelerator frameworks configure scripts have run at this point)
 - the output right now is super confusing for every non-cuda accelerator device. Here is the difference between a configure run with rocm support:

 ```
--- MCA component btl:smcuda (m4 configuration macro)
checking for MCA component btl:smcuda compile mode... dso
checking if --with-cuda is set... not set (--with-cuda=)
checking whether CU_MEM_LOCATION_TYPE_HOST_NUMA is declared... (cached) no
checking if have cuda support... no
checking if MCA component btl:smcuda can compile... yes
```

and without rocm support:
```
--- MCA component btl:smcuda (m4 configuration macro)
checking for MCA component btl:smcuda compile mode... dso
checking if --with-cuda is set... not set (--with-cuda=)
checking whether CU_MEM_LOCATION_TYPE_HOST_NUMA is declared... (cached) no
checking if have cuda support... no
checking if MCA component btl:smcuda can compile... no
```
I would recommend to add an output line that explains that other accelerator support has been found.

2026-03-04 17:34 UTC, bosilca commented
These are both valid observation.
1. The check for CUDa is superfluous. The real assumption is that the accelerator components configure scripts have been already executed (which happens because of the alphabetical order). 
2. I'm afraid there is nothing I can do for the output. The 'no' there is printed outside the component configure.m4, I don't have control over the output without going deep into the weeds on the component discovery.

Maybe the correct approach would be to have an accelerator section up in OMPI configure before we look into components. We can then do the discovery once and then just use the defines to configure the components.

2026-03-05 16:06 UTC, edgargabriel commented
@bosilca I was honestly thinking about just a very simple approach, something like this (ignore the incorrect syntax)

```
AC_DEFUN([MCA_ompi_coll_accelerator_CONFIG],[

    AC_CONFIG_FILES([ompi/mca/coll/accelerator/Makefile])

    OPAL_CHECK_CUDA([coll_accelerator])

    AS_IF([test "x$CUDA_SUPPORT" = "x1"],  
              [],
              [AC_MSG_CHECKING([if other accelerator components were found (rocm, ze)])
               AS_IF([test "x$OMPI_HAVE_ACCELERATOR_SUPPORT" = "x1"],
              [AC_MSG_RESULT([yes]),
              [AC_MSG_RESULT([no])
              ])

    AS_IF([test "x$OMPI_HAVE_ACCELERATOR_SUPPORT" = "x1"],
          [$1],
          [$2])
])dnl

2026-03-07 13:47 UTC, edgargabriel commented
Looks good to me, thank you!

with rocm support 
```
--- MCA component btl:smcuda (m4 configuration macro)
checking for MCA component btl:smcuda compile mode... dso
checking if any accelerator components were found (cuda, rocm, ze)... yes
checking if MCA component btl:smcuda can compile... yes
```

without rocm support
```
--- MCA component btl:smcuda (m4 configuration macro)
checking for MCA component btl:smcuda compile mode... dso
checking if any accelerator components were found (cuda, rocm, ze)... no
checking if MCA component btl:smcuda can compile... no
```

2026-03-09 16:06 UTC, merged

2026-03-10 15:01 UTC, edgargabriel commented
@bosilca could you please cherry-pick this to the 6.0.x branch?