Fix mpirun.1.rst typos
open-mpi/ompi pull request #12937
Opened 2024-11-26 19:42 UTC by jsquyres

Thanks to @satishskamath for raising the issue.

Refs #12936 

@rhc54 Can you confirm the PRRTE / PRTE fixes on this PR?  (restricted to the 1st commit)

2024-11-26 20:50 UTC, rhc54 requested changes
Few minor corrections. Do you also cover PMIx params in here somewhere? I didn't see them mentioned.

2024-11-26 20:50 UTC, rhc54 commented on docs/man-openmpi/man1/mpirun.1.rst
> +the PRRTE runtime so the command line argument ``--prte-mca``
It is `--prtemca` - all one word

2024-11-26 20:50 UTC, rhc54 commented on docs/man-openmpi/man1/mpirun.1.rst
> +non-zero status. The MCA parameter ``--prte-mca state_base_error_non_zero_exit``
Ditto here - it is `--prtemca`

2024-11-26 20:50 UTC, rhc54 commented on docs/man-openmpi/man1/mpirun.1.rst
> +  example, specifying a launch agent of ``prted --mca odls_base_verbose
Your example isn't quite correct here - it should be `--prtemca odls_base_verbose 5`.  Using the generic `mca` leaves open the possibility that `prted` will misinterpret the intent.

2024-11-26 21:28 UTC, jsquyres commented
Thanks @rhc54 -- fixed.

2024-11-26 23:46 UTC, jsquyres commented
Hey @rhc54 -- I added blurbs about `--pmixmca` and `--prtemca`.  Do those look ok?

2024-11-27 00:11 UTC, rhc54 commented
> Hey @rhc54 -- I added blurbs about `--pmixmca` and `--prtemca`. Do those look ok?

Definitely!! Thanks!

2024-12-02 23:30 UTC, merged