PML/UCX/WPOOL: fixed coverity issue
open-mpi/ompi pull request #8219
Opened 2020-11-16 08:30 UTC by hoopoepg

- fixed issue reported by coverity

2020-11-17 15:43 UTC, devreal approved these changes

2020-11-17 15:45 UTC, artpol84 requested changes

2020-11-17 15:45 UTC, artpol84 commented on opal/mca/common/ucx/common_ucx_wpool.c
>      ucp_cleanup(wpool->ucp_ctx);
```suggestion
    OBJ_DESTRUCT(&wpool->active_workers);
    OBJ_DESTRUCT(&wpool->active_workers);
    ucp_cleanup(wpool->ucp_ctx);
```

2020-11-17 15:47 UTC, devreal commented on opal/mca/common/ucx/common_ucx_wpool.c
>      ucp_cleanup(wpool->ucp_ctx);
Typo? (one should be `idle_workers`)

```suggestion
    OBJ_DESTRUCT(&wpool->idle_workers);
    OBJ_DESTRUCT(&wpool->active_workers);
    ucp_cleanup(wpool->ucp_ctx);
```

2020-11-17 15:54 UTC, hoopoepg commented on opal/mca/common/ucx/common_ucx_wpool.c
>      ucp_cleanup(wpool->ucp_ctx);
updated PR

2020-11-17 16:02 UTC, artpol84 approved these changes

2020-11-17 16:05 UTC, artpol84 commented
@hoopoepgneed the Sign-off in the second commit

2020-11-17 16:09 UTC, hoopoepg commented
every time forget to sign it :)

2020-11-17 16:10 UTC, artpol84 commented
@janjust FYI
Need to rebase https://github.com/open-mpi/ompi/pull/8212

2020-11-18 14:04 UTC, hoopoepg commented
bot:retest

2020-11-21 01:31 UTC, merged