Fix MPIR regression with extern MPIR_proctable.
open-mpi/ompi pull request #8570
Opened 2021-03-09 13:52 UTC by awlauria

Signed-off-by: Austen Lauria <awlauria@us.ibm.com>

Fixes #8563

bot:notacherrypick

2021-03-09 16:17 UTC, hppritcha approved these changes

2021-03-10 12:58 UTC, jjhursey approved these changes

2021-03-10 14:15 UTC, jsquyres requested changes
Please see https://github.com/open-mpi/ompi/pull/8571#pullrequestreview-608757347

2021-03-12 22:35 UTC, awlauria commented
@jsquyres updated. if that looks good I'll move it to the other release branches (v3.1.x/v4.1.x)

2021-03-12 22:38 UTC, jsquyres approved these changes
@louisespellacy-arm Can you confirm that this PR fixes the issue for you?

2021-03-13 20:15 UTC, hppritcha commented
bot:ompi:retest

2021-03-15 10:59 UTC, louisespellacy-arm commented
Fixes issue for me when I build pull request.

2021-03-15 15:26 UTC, gpaulsen approved these changes

2021-03-15 15:26 UTC, merged