Topic/fix data type issue
open-mpi/ompi pull request #8859
Opened 2021-04-26 20:57 UTC by hppritcha

Brings some updates on the datatype engine into the 4.0. Among these the most critical is the partial unpack bug from #8466. 

Here are the commits from master that are covered by this PR:
e8ebe134450752188362c8d5cc524ea79d27fa24
99013253954f383e241fc261f7ca4291e2316ef6
ef28e8d98101d9fcc5e92ff14cbe0afa828f2538
73d64cb97b48c4c6860aa0d49af9705349d6f64b
fb0796020e90ebb068bfda39f8af98c7146ebc9c

It must be noted that this PR does not bring the support for MPI_LONG and MPI_UNSIGNED_LONG in external32, because it would have required to break the ABI (because of the 2 new datatypes #define added).

Unfortunately, I had to import 2 additional commits in order to be able to build and run on an M1: 4f2dde0 and 73aae14.  

Fixes #8466.

One of these commits is intentionally not a cherry pick: bot:notacherrypick

2021-04-26 21:42 UTC, gpaulsen commented
Hmm Mellanox  (https://dev.azure.com/mlnx-swx/mellanox-ompi/_build/results?buildId=2782&view=logs&j=05ee1795-5e75-566a-c260-61630d0851a3&t=c5df7113-1021-5252-6808-853389e8d517&l=18904) failed with:
```
../../config/test-driver: line 107:  3193 Aborted                 (core dumped) "$@" > $log_file 2>&1
FAIL: partial
```

Also check out https://github.com/open-mpi/ompi/pull/8845, as that may resolve this???

2021-04-27 15:35 UTC, hppritcha commented
i'm able to reproduce the fpe on x86_64.

2021-04-27 16:02 UTC, hppritcha commented
looks like I didn't resolve a conflict correctly.

2021-04-28 03:06 UTC, gpaulsen requested changes
@hppritcha I noticed two differences between this PR and PR #8769 on master.

Marking this as Request change, but really just need to look at more closely.

2021-04-29 15:23 UTC, hppritcha commented
@gpaulsen repushed

2021-05-03 19:39 UTC, gpaulsen commented
@hppritcha,  @bosilca suggested we hold off on merging the v5.0.x version of this PR https://github.com/open-mpi/ompi/pull/8891#issuecomment-829764905 until we know more.  I assume we should hold off on this a little while longer as well?

2021-05-04 14:31 UTC, hppritcha commented
sure we can wait

2021-05-18 15:17 UTC, bosilca approved these changes

2021-05-21 18:15 UTC, gpaulsen approved these changes

2021-05-21 18:27 UTC, merged