Ensure that libdir is always first in search path
open-mpi/ompi pull request #9029
Opened 2021-06-02 21:31 UTC by bwbarrett

Switch the ordering of both the -L and rpath/runpath arguments
added by the wrapper compiler so that the install's libdir
is always the first in the list of paths to search.  Previously,
the component-related paths were added first, which could cause
applications to find an errant (to us, anyway) libmpi.

Signed-off-by: Brian Barrett <bbarrett@amazon.com>
(cherry picked from commit bed9f202132b9451f60d4a72ace95fe9b88f8c75)
(cherry picked from commit 99c795dbfdb1d2174f2fd8fe8360526255d1b2c3)

2021-06-02 21:32 UTC, bwbarrett commented
The cherry pick is from the v4.1 branch, since pulling directly from master would create conflicts I already fixed in the 4.1 backport.

Refs https://github.com/open-mpi/ompi/issues/8990

2021-06-02 22:00 UTC, jsquyres approved these changes

2021-06-03 14:13 UTC, hppritcha commented
i'm assuminng the github cherry pick checker is confused about having two cherry-picked from strings so ignoring this failure.

2021-06-03 14:16 UTC, bwbarrett commented
> i'm assuminng the github cherry pick checker is confused about having two cherry-picked from strings so ignoring this failure.

No, I think it's actually doing the right thing.  The second cherry pick line is from the v4.1.x branch, but the commit hasn't been pushed on that branch yet.  I'll sort it out once https://github.com/open-mpi/ompi/pull/9028 is pushed.

2021-06-03 14:23 UTC, hppritcha commented
we are wanting to get a release tagged today so did some editing of the commit to fool the cherry-pick checker.

2021-06-03 14:30 UTC, jsquyres requested changes
Howard -- what is this line in the commit message:

```
(also from - fool cherrypicker 99c795d)
```

Please do not do that.

2021-06-03 14:33 UTC, jsquyres commented
Just to be clear: the git commit checker is doing exactly what it is supposed to be doing.  It is not allowing you to say that this is a cherry pick of abc123 until commit abc123 actually exists in the Open MPI repository (i.e., until the PR where it came from is merged).

2021-06-03 14:33 UTC, bwbarrett commented
I committed the v4.1 change and repushed to the original commit.  Not unsurprisingly, the commit checker passes now.  No need for silly hacks; the system worked as expected.

2021-06-03 14:38 UTC, jsquyres approved these changes

2021-06-03 14:40 UTC, jsquyres commented
> we are wanting to get a release tagged today so did some editing of the commit to fool the cherry-pick checker.

If you guys need a 4.1 PR merged for situations like this, just ask.  @bwbarrett merged #9028, which made the git cherry pick checker happy.

2021-06-03 15:26 UTC, hppritcha commented
we want to get this in and tag the branch to generate a 4.0.6rc3 tarball this evening.

2021-06-03 20:02 UTC, merged