Fix --prefix option in mpirun.
open-mpi/ompi pull request #9136
Opened 2021-07-12 19:19 UTC by awlauria

Tack "/bin" back on the end of the --prefix line to preserve old
behavior.

2021-07-12 19:24 UTC, bwbarrett requested changes
this is not the right way to solve this problem.  This is what installdirs is for.

2021-07-12 19:58 UTC, rhc54 approved these changes
Actually, I believe @awlauria is correct here. Installdirs is for when you specify the prefix at configure time. This code path is for when you specify `--prefix` on the `mpirun` cmd line. In that case, we always left off the "bin" portion since we also used to set the `LD_LIBRARY_PATH` as well.

So this does in fact restore the prior behavior.

2021-07-13 02:30 UTC, bwbarrett approved these changes
I disagree with Ralph; this is what installdirs is for (as you should be able to properly handle --prefix=/tmp/foobar and bindir=${prefix}/x86_64/bin), but given that this just reimplements the previous behavior, let's go with it.

2021-07-13 02:33 UTC, rhc54 commented
I don't have a hard opinion here, Brian - IIUC, you are saying that we should take the cmd line prefix and append the installdirs "bin" to it? Just trying to understand how you think the cmd line prefix option should be implemented.

2021-07-13 13:02 UTC, awlauria commented
I have no opinion either. I can change the PR if there is a better way to accomplish this.

2021-07-13 14:41 UTC, bwbarrett commented
nope; let's merge this and keep existing behavior, since people haven't been complaining.

2021-07-13 14:49 UTC, merged