OMPI/COLL: Add allgather coll ucc
open-mpi/ompi pull request #9152
Opened 2021-07-19 14:02 UTC by lappazos

2021-07-19 14:15 UTC, bwbarrett commented
ok to test

2021-07-19 15:38 UTC, ibm-ompi commented
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ab0635a8ef1f4f31ed8448747ce307d5

2021-07-19 16:39 UTC, jjhursey commented
bot:ibm:retest

2021-07-20 06:33 UTC, vspetrov requested changes

2021-07-20 06:33 UTC, vspetrov commented on ompi/mca/coll/ucc/coll_ucc.h
> +    mca_coll_base_module_alltoall_fn_t   previous_allgather;
alltoall_fn_t -> allgather_fn_t
ialltoall_fn_t ->iallgather_fn_t

2021-07-20 06:33 UTC, vspetrov commented on ompi/mca/coll/ucc/coll_ucc_allgather.c
> +    return ucc_module->previous_iallgather(sbuf, scount, sdtype, rbuf, rcount, rdtype,
we have a leak of coll_req here (it was in the original coll/ucc implementation). If we go to fallback then coll_req might leak. Please set coll_req to NULL in line 92. Then before line 104 check:
if (coll_req) {
mca_coll_ucc_req_free(coll_req);
}
"previous_iallgather" will allocate the request itself.

Also please check & apply the same fix to ALL other non-blocking coll/ucc collectives

2021-07-20 06:33 UTC, vspetrov commented on ompi/mca/coll/ucc/coll_ucc_allgatherv.c
> +        .flags = UCC_COLL_ARGS_FLAG_CONTIG_SRC_BUFFER |
how can you assume it is that the buffers are CONTIG? i think it is not correct unless you perform O(N) check.

2021-07-23 14:20 UTC, gpaulsen commented
@lappazos Could you please sign off the commits in this Pull Request using the `-s` flag to `git commit`?  By doing so, you and your company agree to https://github.com/open-mpi/ompi/wiki/Administrative-rules#contributors-declaration.  This will also allow the GitHub Action CI / Git commit checker to pass.

2021-07-30 08:05 UTC, vspetrov approved these changes

2021-07-30 08:05 UTC, vspetrov commented on ompi/mca/coll/ucc/coll_ucc_reduce.c
> +													mca_coll_ucc_module_t *ucc_module,
alignment

2021-07-30 14:23 UTC, janjust approved these changes

2021-08-03 12:26 UTC, lappazos commented
@gpaulsen any idea why the check is stuck?

2021-08-03 12:41 UTC, awlauria commented
@lappazos fixed.

2021-08-03 15:13 UTC, janjust commented
@lappazos can you please open up a v5.0 of this PR

2021-08-03 15:14 UTC, merged

2021-08-03 21:50 UTC, lappazos commented
> @lappazos can you please open up a v5.0 of this PR (please remember to use the -s -x arguments to add the cherry-pick and signoff info)

@janjust @awlauria should I cherry-pick the commit from my own branch (the commit i pushed here), or the new merge commit from master?

2021-08-03 22:01 UTC, lappazos commented
> @lappazos can you please open up a v5.0 of this PR (please remember to use the -s -x arguments to add the cherry-pick and signoff info)

Done