Add a framework and components to expose shared memory single copy to all components
open-mpi/ompi pull request #9154
Opened 2021-07-19 19:04 UTC by hjelmn

This PR moves the shared-memory single-copy code out of btl/sm and puts it in its own framework. This will allow other components to make use of this functionality without relying on btl/sm.

2021-07-24 00:00 UTC, bwbarrett submitted a review, later dismissed
Overall, looks like a massive improvement.  A couple of nits included.

One larger question...  In the unlikely scenario that two processes come to different smsc selection answers, it looks like we're going to handle that poorly.  Maybe I'm reading the code wrong, but only one of the `get_endpoint()` calls seems to check the other side is actually using the same smsc.  Am I reading that wrong?

2021-07-24 03:41 UTC, hjelmn commented on opal/mca/smsc/Makefile.am
> +AM_CPPFLAGS = $(LTDLINCL)
Done.

2021-07-24 03:42 UTC, hjelmn commented on opal/mca/smsc/Makefile.am
> +AM_CPPFLAGS = $(LTDLINCL)
Hmm. Got to remember this isn't piper. Will be fixed when i push the changes :)

2021-07-24 03:44 UTC, hjelmn commented on opal/mca/smsc/Makefile.am
> +# Copyright (c) 2021      Google, LLC. All rights reserved.
Copy-and-paste from another Makefile.am. Fixing.

2021-07-27 19:25 UTC, gpaulsen commented
We discussed this in the Web-ex Today.  Consensus was that it'd be good to get this into v5.0 as there are other optimizations and code-cleanup that Nathan's working on that this will enable.

2021-07-28 17:00 UTC, hjelmn commented on opal/mca/smsc/Makefile.am
> +AM_CPPFLAGS = $(LTDLINCL)
Done.

2021-07-28 17:00 UTC, hjelmn commented on opal/mca/smsc/Makefile.am
> +# Copyright (c) 2021      Google, LLC. All rights reserved.
Done.

2021-07-28 17:03 UTC, hjelmn commented on opal/mca/smsc/base/smsc_base_impl.c
> +int mca_smsc_base_copy_to(mca_smsc_endpoint_t *endpoint, void *local_address, void *remote_address,
Done. Now handled in such a way to allow MCA direct (which was broken BTW-- another PR fixes it).

2021-07-28 17:03 UTC, hjelmn commented on opal/mca/smsc/base/smsc_base_impl.c
> +        fprintf(stderr, "XXX No module\n");
Debug code. File removed. No longer relevant.

2021-07-28 17:08 UTC, hjelmn commented on opal/runtime/opal_init.c
> +    &opal_hwloc_base_framework,
clang-format put them one per line. More readable that way but it does hide what changed. Reverted just the style change.

2021-07-28 17:08 UTC, hjelmn commented on opal/mca/smsc/base/smsc_base_frame.c
> +                                "mca_smsc_base_select: could not select component %s. enable "
Done.

2021-07-28 17:09 UTC, ibm-ompi commented
The IBM CI (PGI) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

2021-08-01 22:10 UTC, jsquyres requested changes
I get this warning when compiling:

```
2032 make[2]: Entering directory `/home/jsquyres/git/ompi/opal/mca/smsc'
2033   CC       base/smsc_base_frame.lo
2034 In file included from ../../../opal/mca/smsc/base/base.h:14,
2035                  from base/smsc_base_frame.c:27:
2036 ../../../opal/mca/smsc/smsc.h:216:5: warning: "MCA_opal_smsc_DIRECT_CALL" is not defined, evaluates to 0 [-Wundef]
2037  #if MCA_opal_smsc_DIRECT_CALL
2038      ^~~~~~~~~~~~~~~~~~~~~~~~~
```

(repeats for all the BTL SM + SMSC component source files, too)

Feels like that is significant...

2021-08-11 19:20 UTC, hjelmn commented
@jsquyres Fixed. File missing from one of the commits. Please re-test.

2021-08-12 13:11 UTC, jsquyres approved these changes
Warning fixed.

2021-08-12 15:05 UTC, merged