odls/base: Fix abormal cleanup when app is wrapped
open-mpi/ompi pull request #9261
Opened 2021-08-17 15:41 UTC by awlauria

* The scenario is that we have a wrapper process placed before the
   MPI application:
```shell
 mpirun -np 2 wrapper ./hello_c
```
 * If `hello_c` crashes and `wrapper` detects it, then `wrapper` will
   exit with a non-zero exit status. The orted will notice that and
   start a kill process for all local processes.
   - The orted will send `SIGKILL` to the `wrapper` process, and that
     process will terminate and leave the `hello_c` running. The `hello_c`
     will continue to run (in this test case will wait in `MPI_Finalize`)
     and the job will seem to hang.
 * This commit does two things each will fix this scenario.
   1. After killing the process mark it as not alive since we are not
      going to wait on it. This prevents orted_cmd from seeing the process
      as alive and waiting for it to complete (note that the pid is set
      to `0` so we wouldn't be able to mark it correctly later even if
      we did get a notice.
   2. Instead of sending the `SIGKILL` signal to just the `PID` of `wrapper`
      send it to `-PID` so that the kernel will send the signal to the
      whole process group under `wrapper` as well. This will case the
      `hello_c` program to terminate as well.

bot:notacherrypick

Signed-off-by: Austen Lauria <awlauria@us.ibm.com>

2021-08-17 16:27 UTC, jjhursey commented
From `man 3 kill`

>       If pid is negative, but not -1, sig shall be sent to all processes (excluding an  unspeci‐
>       fied  set  of  system  processes) whose process group ID is equal to the absolute value of
>       pid, and for which the process has permission to send a signal.

The goal here is to send the signal to the whole process tree under the pid. In this case the PID is that of the wrapper command, and we want the signal to also go to the process being wrapped.

2021-08-17 16:27 UTC, jjhursey approved these changes

2021-08-17 16:36 UTC, awlauria commented
I'll make a note to check if this needs to be ported to prrte.

2021-08-17 20:34 UTC, gpaulsen approved these changes

2021-08-18 02:09 UTC, rhc54 commented
This change is incorrect - we already have done this for years. It is done in the odls/default component:
```c
static int odls_default_kill_local(pid_t pid, int signum)
{
    pid_t pgrp;

#if HAVE_SETPGID
    pgrp = getpgid(pid);
    if (-1 != pgrp) {
        /* target the lead process of the process
         * group so we ensure that the signal is
         * seen by all members of that group. This
         * ensures that the signal is seen by any
         * child processes our child may have
         * started
         */
        pid = -pgrp;
    }
#endif
```
We always put each application proc in its own process group so signals hitting the daemons don't get transferred to the application. We then ensure that we hit the entire process group with any signal we are asked to deliver.

2021-08-18 02:13 UTC, rhc54 requested changes
Please do not merge as this is incorrect.

2021-08-18 11:58 UTC, awlauria commented
@rhc54 it looks like your fix went in a few months after @jjhursey's .

https://github.com/open-mpi/ompi/commit/c6c0258cd882d34de36a3404a383d8f77c7be18f

I'll verify and close this and the v4.1 version today. 

This change never went into upstream ompi, just something we have had in SMPI and not upstreamed until now. Thanks for catching

2021-08-18 13:46 UTC, awlauria commented
Verified this works on current v4.0.x

2021-08-18 13:46 UTC, closed without merging