v4.1.x: Select all adapters with IPV4 addresses within specified subnet ranges.
open-mpi/ompi pull request #9756
Opened 2021-12-07 21:01 UTC by drwootton

This pull request is a cherry-pick of master branch pull requests #9681 and #9710 into the v4.1.x branch so that all interfaces within the specified subnet range can be selected by the the -mca btl_tcp_if_include and btl_tcp_if_exclude options. Including #9710 fixes for Coverity problems in #9681.

2021-12-07 21:03 UTC, jjhursey commented
ok to test

2021-12-07 21:07 UTC, jjhursey commented
We will need a similar patch against `orte/mca/oob/tcp` in this PR.

2021-12-08 19:40 UTC, jjhursey commented
This PR includes a cherry-pick of PR #9681 and additional fixes to ORTE and the embedded PMIx. The ORTE and PMIx changes are not cherry picks since they do not exist on master/v5.0.x.

2021-12-08 20:17 UTC, jjhursey approved these changes

2021-12-08 20:23 UTC, jjhursey commented
This is ready for review by the v4.1.x RMs.

A couple of notes:
 * Commits 1 and 2 are the cherry-picks from OMPI. Changes to btl/tcp
 * Commit 3 is the ORTE version of the PRTE commit. So the oob/tcp has consistent behavior with OMPI.
   * https://github.com/openpmix/prrte/pull/1161
 * Commit 4 changes the embedded PMIx version to be consistent with ORTE/OMPI in ptl/tcp.
   * https://github.com/openpmix/openpmix/pull/2404

The question to the RMs is if they want Commit 4 (modification to embedded OpenPMIx) or not. The OpenPMIx change https://github.com/openpmix/openpmix/pull/2404 only went to `master` but we ask if they would entertain cherry-picking it to the v3 release. Alternatively, we could drop that 4th commit and keep OMPI and ORTE consistent. I'm not sure how many folks will notice the OpenPMIx change.

2021-12-08 20:25 UTC, rhc54 commented
Given that neither ORTE nor PMIx "stripe" messages across multiple interfaces, it's hard to see how those changes would impact anything. We only use one interface regardless of how many might be around.

2021-12-15 03:08 UTC, jsquyres commented
I'm ok with commits 1-3.  I agree with @rhc54's point that ORTE doesn't ever use more than one interface, but the consistency between BTL and OOB is a good thing.

I'm conflicted about the 4th commit (the PMIX change), though.
* Pros:
    * It went in on PMIx master.
    * Consistency with ORTE and BTL is a good thing.
* Cons:
    * It makes the PMIx in v4.1.x be a bit different than the upstream PMIx 3.2.3 that 0e36e48f5328c025b6ea529ab96e3bbdcda55d6a says that it is.

@bwbarrett Got an opinion here?

2021-12-15 03:11 UTC, rhc54 commented
Note: I'm not opposed to backporting it to PMIx 3.2.x and doing another 3.2 release. Just doesn't really do anything in terms of impacting behavior. But if it means something to you folks, we can certainly do it as it doesn't change the PMIx 3.2 series observable behavior.

2021-12-17 15:20 UTC, jsquyres requested changes
We chatted offline about this.

Could you remove the PMIx commit from this PR?

I'm ambivalent about the ORTE commit -- feel free to keep it or feel free to delete it.

Thanks for the due diligence!

2021-12-17 15:50 UTC, jjhursey commented
@drwootton is out until after the new year. I went ahead and dropped the OpenPMIx commit on his branch. This should be ready for review.

2021-12-17 15:59 UTC, jsquyres approved these changes

2021-12-17 18:57 UTC, merged